from tkinter import font

H1 = font.Font(family="Microsoft YaHei UI", size=28, weight="bold")
H2 = font.Font(family="Microsoft YaHei UI", size=24, weight="bold")
H3 = font.Font(family="Microsoft YaHei UI", size=20, weight="bold")
H4 = font.Font(family="Microsoft YaHei UI", size=16, weight="bold")
H5 = font.Font(family="Microsoft YaHei UI", size=14, weight="bold")
H6 = font.Font(family="Microsoft YaHei UI", size=12, weight="bold")
P = font.Font(family="Microsoft YaHei UI", size=12)
P_SMALL = font.Font(family="Microsoft YaHei UI", size=10)
P_LARGE = font.Font(family="Microsoft YaHei UI", size=16)
P_BOLD = font.Font(family="Microsoft YaHei UI", size=12, weight="bold")
P_BOLD_SMALL = font.Font(family="Microsoft YaHei UI", size=10, weight="bold")
P_BOLD_LARGE = font.Font(family="Microsoft YaHei UI", size=16, weight="bold")
P_ITALIC = font.Font(family="Microsoft YaHei UI", size=12, slant="italic")
P_UNDERLINE = font.Font(family="Microsoft YaHei UI", size=12, underline=True)
P_STRIKE = font.Font(family="Microsoft YaHei UI", size=12, overstrike=True)
P_MONO = font.Font(family="Consolas", size=12)
P_MONO_SMALL = font.Font(family="Consolas", size=10)
P_MONO_LARGE = font.Font(family="Consolas", size=16)
P_MONO_BOLD = font.Font(family="Consolas", size=12, weight="bold")
P_MONO_BOLD_SMALL = font.Font(family="Consolas", size=10, weight="bold")
P_MONO_BOLD_LARGE = font.Font(family="Consolas", size=16, weight="bold")
P_MONO_ITALIC = font.Font(family="Consolas", size=12, slant="italic")
P_MONO_UNDERLINE = font.Font(family="Consolas", size=12, underline=True)
P_MONO_STRIKE = font.Font(family="Consolas", size=12, overstrike=True)